local M = require("dvim.utils.functions")

M.safe_require("dvim.settings.options")
M.safe_require("dvim.settings.keymaps")
M.safe_require("dvim.settings.plugins")
M.safe_require("dvim.settings.colorscheme")

M.safe_require("dvim.config.alpha")
M.safe_require("dvim.config.autocommands")
M.safe_require("dvim.config.autopairs")
M.safe_require("dvim.config.bufferline")
M.safe_require("dvim.config.cmp")
M.safe_require("dvim.config.comment")
M.safe_require("dvim.config.cybu")
M.safe_require("dvim.config.dap")
M.safe_require("dvim.config.gitsigns")
M.safe_require("dvim.config.gps")
M.safe_require("dvim.config.icons")
M.safe_require("dvim.config.impatient")
M.safe_require("dvim.config.jabs")
M.safe_require("dvim.config.lsp")
M.safe_require("dvim.config.lualine")
M.safe_require("dvim.config.lualine")
M.safe_require("dvim.config.markdown")
M.safe_require("dvim.config.neogen")
M.safe_require("dvim.config.nvim-tree")
M.safe_require("dvim.config.project")
M.safe_require("dvim.config.surround")
M.safe_require("dvim.config.symbols-outline")
M.safe_require("dvim.config.telescope")
M.safe_require("dvim.config.todo-comments")
M.safe_require("dvim.config.toggleterm")
M.safe_require("dvim.config.treesitter")
M.safe_require("dvim.config.ultisnips")
M.safe_require("dvim.config.vimtex")
M.safe_require("dvim.config.which-key")
M.safe_require("dvim.config.winbar")
