local M = require("SingularisArt.functions")

M.safe_require("SingularisArt.options")
M.safe_require("SingularisArt.keymaps")
M.safe_require("SingularisArt.plugins")
M.safe_require("SingularisArt.colorscheme")

M.safe_require("SingularisArt.alpha")
M.safe_require("SingularisArt.autocommands")
M.safe_require("SingularisArt.autopairs")
M.safe_require("SingularisArt.bufferline")
M.safe_require("SingularisArt.cmp")
M.safe_require("SingularisArt.comment")
M.safe_require("SingularisArt.cybu")
M.safe_require("SingularisArt.dap")
M.safe_require("SingularisArt.gitsigns")
M.safe_require("SingularisArt.gps")
M.safe_require("SingularisArt.icons")
M.safe_require("SingularisArt.impatient")
M.safe_require("SingularisArt.jabs")
M.safe_require("SingularisArt.lsp")
M.safe_require("SingularisArt.lualine")
M.safe_require("SingularisArt.markdown")
M.safe_require("SingularisArt.neogen")
M.safe_require("SingularisArt.nvim-tree")
M.safe_require("SingularisArt.project")
M.safe_require("SingularisArt.surround")
M.safe_require("SingularisArt.symbols-outline")
M.safe_require("SingularisArt.telescope")
M.safe_require("SingularisArt.todo-comments")
M.safe_require("SingularisArt.toggleterm")
M.safe_require("SingularisArt.treesitter")
M.safe_require("SingularisArt.ultisnips")
M.safe_require("SingularisArt.vimtex")
M.safe_require("SingularisArt.which-key")
M.safe_require("SingularisArt.winbar")
