local M = require("dvim.utils.functions")
Utils = require("dvim.utils.functions")

dvim = require("dvim.config")
dvim = dvim.dvim

M.safe_require("dvim.settings.options")
M.safe_require("dvim.settings.keymaps")
M.safe_require("dvim.settings.plugins")
M.safe_require("dvim.settings.colorscheme")
M.safe_require("dvim.settings.autocommands")

M.safe_require("dvim.core.alpha")
M.safe_require("dvim.core.autopairs")
M.safe_require("dvim.core.bufferline")
M.safe_require("dvim.core.cmp")
M.safe_require("dvim.core.comment")
M.safe_require("dvim.core.cybu")
M.safe_require("dvim.core.dap")
M.safe_require("dvim.core.gitsigns")
M.safe_require("dvim.core.gps")
M.safe_require("dvim.core.icons")
M.safe_require("dvim.core.impatient")
M.safe_require("dvim.core.jabs")
M.safe_require("dvim.core.lsp")
M.safe_require("dvim.core.lualine")
M.safe_require("dvim.core.lualine")
M.safe_require("dvim.core.markdown")
M.safe_require("dvim.core.neogen")
M.safe_require("dvim.core.nvim-tree")
M.safe_require("dvim.core.project")
M.safe_require("dvim.core.surround")
M.safe_require("dvim.core.symbols-outline")
M.safe_require("dvim.core.telescope")
M.safe_require("dvim.core.todo-comments")
M.safe_require("dvim.core.toggleterm")
M.safe_require("dvim.core.treesitter")
M.safe_require("dvim.core.ultisnips")
M.safe_require("dvim.core.vimtex")
M.safe_require("dvim.core.which-key")
M.safe_require("dvim.core.notify")
M.safe_require("dvim.core.winbar")
