return {
  actions = {
    writing = {},
    note_taking = {},
    programming = {},
    presentation = {},
    documentation = {},
  },
  plugins = {
    alpha = {},
    indent_blankline = {},
    symbols_outline = {},
    which_key = {
      mappings = {},
      user_vmappings = {},
      user_mappings = {},
      presets = {},
      spelling = {},
    },
    gitsigns = {},
    comment = {},
    surround = {},
    todo_comments = {},
    terminal = {},
    dap = {},
    ultisnips = {},
    telescope = {
      extensions = {}
    },
    project = {},
    copilot = {},
    cmp = {},
    autopairs = {},
    nvimtree = {},
    lualine = {},
    staline = {},
    bufferline = {},
    notify = {},
    treesitter = {},
    folds = {},
  },
  filetypes = {
    lua = {},
    vim = {},
    python = {},
    cpp = {},
    cmake = {},
    c = {},
    c_sharp = {},
    sql = {},
    html = {},
    css = {},
    javascript = {},
    typescript = {},
    php = {},
    ruby = {},
    perl = {},
    java = {},
    rust = {},
    solidity = {},
    go = {},
    bash = {},
    log = {},
    latex = {},
    markdown = {},
    yaml = {},
    json = {},
    toml = {},
    tmux = {},
  },
}
