-- local saga = SingularisArt.call('lspsaga', 'LSP Saga')
--
-- saga.init_lsp_saga {
-- }
--
-- saga.init_lsp_saga {
--   error_sign = '',
--   warn_sign = '',
--   hint_sign = '',
--   infor_sign = '',
--   diagnostic_header_icon = ' ',
--   code_action_icon = ' ',
--   code_action_prompt = {
--     enable = true,
--     sign = true,
--     sign_priority = 20,
--     virtual_text = true,
--   },
--   finder_definition_icon = '  ',
--   finder_reference_icon = '  ',
--   max_preview_lines = 10,
--   finder_action_keys = {
--     open = 'o', vsplit = 's',split = 'i',quit = 'q',scroll_down = '<C-f>', scroll_up = '<C-b>' -- quit can be a table
--   },
--   code_action_keys = {
--     quit = 'q',exec = '<CR>'
--   },
--   rename_action_keys = {
--     quit = '<C-c>',exec = '<CR>'  -- quit can be a table
--   },
--   definition_preview_icon = ' ',
--   border_style = "double",
--   rename_prompt_prefix = '➤',
-- }
--
-- -- vim.lsp.handlers["textDocument/publishDiagnostics"] = vim.lsp.with(
-- --   vim.lsp.diagnostic.on_publish_diagnostics, {
-- --     underline = true,
-- --     signs = true,
-- --     update_in_insert = false,
-- --     severity_sort = true,
-- --     -- This sets the spacing and the prefix, obviously.
-- --     virtual_text = {
-- --       source = 'if_many',
-- --       spacing = 10,
-- --       prefix = ' '
-- --     },
-- --     float = {
-- --       source = 'if_many',
-- --       border = 'rounded',
-- --     },
-- --   }
-- -- )
--
-- vim.diagnostic.config({
--   virtual_text = false,
-- })
